### ISSUE TITLE
setup_drchecker clones LLVM projects in wrong directories

### ISSUE THREAD

**Issue by ajdlinux** [ucsb-seclab/dr_checker#2]
`setup_drchecker.py` clones some LLVM subprojects:

    reps_to_setup = {'tools': ['clang'], 'projects': ['compiler-rt', 'libcxx', 'libcxxabi', 'openmp']}

    ...

    for curr_folder in reps_to_setup:
        dst_folder = os.path.join(base_output_dir, curr_folder)
        for curr_rep in reps_to_setup[curr_folder]:
            dst_folder = os.path.join(dst_folder, curr_rep)
            git_clone_cmd = "git clone " + LLVM_GIT_HUB_BASE + str(curr_rep) + " -b " + \
                            str(target_branch) + " " + dst_folder
            log_info("Setting up ", curr_rep, " repo.")
            os.system(git_clone_cmd)

It looks to me like it should be cloning `clang` in `tools/`, and `compiler-rt`, `libcxx`, `libcxxabi` and `openmp` in `projects/` - but for the repositories in `projects/`, it's just appending the new repository name to the existing path string, such that we end up cloning `openmp` in `projects/compiler-rt/libcxx/libcxxabi/openmp`.

**Comment by Machiry** [comment]
You are right @ajdlinux. Fix pushed. Thanks.
