### ISSUE TITLE
Soundy Analysis failed for all entrypoints

### ISSUE THREAD

**Issue by willsheil** [ucsb-seclab/dr_checker#20]
Is there any log files for analyzing this issue?
.....................
[!]  Soundy Analysis failed for: attr_set_cap_prox_enable
[!]  Soundy Analysis failed for: attr_set_cap_prox_delay
[!]  Soundy Analysis failed for: attr_set_rdr_test
[!]  Soundy Analysis failed for: shb_read
[!]  Soundy Analysis failed for: shb_write
[!]  Soundy Analysis failed for: shb_ioctl
[*]  **Soundy Analysis failed for: 347  out of: 347  entry points.**
[+]  Component: SoundyAnalysisRunner  ran successfully.
[+]  Component: SoundyAnalysisRunner  passed successfully.
[*]  Trying to Run Component: ComputeWarningStats
[+]  Setup for component: ComputeWarningStats  complete
[*]  Invoking Warnings Stats Computation.

**Comment by Machiry** [comment]
The log files are the <entry_point_name>.txt file for each entry point and they will be in the SOUNDY_ANALYSIS_OUT directory. Can you share one of them?

**Comment by willsheil** [comment]
Hi:
There are many *.out file generated in the SOUNDY_ANALYSIS_OUT directory,but no <entry_point_name>.txt file exists.Only one file named log.txt is in this directory,but the content is empty.

**Comment by Machiry** [comment]
Sorry. Can you share the .out files?

**Comment by willsheil** [comment]
Hi:
all the .out files content seem like this,maybe some wrong with llvm
opt: Unknown command line argument '-debug'.  Try: '/root/llvm-3.8.0/bin/opt -help'
opt: Did you mean '-tbaa'?
opt: Unknown command line argument '-debug'.  Try: '/root/llvm-3.8.0/bin/opt -help'
opt: Did you mean '-tbaa'?

**Comment by Machiry** [comment]
That is strange. `-debug` is allowed an option for opt. Try removing `-debug` in the line: https://github.com/ucsb-seclab/dr_checker/blob/speedy/helper_scripts/runner_scripts/components/soundy_analysis_runner.py#L119 and run again?

**Comment by willsheil** [comment]
Thanks,it works!
