### ISSUE TITLE
What the dangerous for "Trying to use a global variable without locking."

### ISSUE THREAD

**Issue by leiwen83** [ucsb-seclab/dr_checker#27]
Hi,
I see lots of warns with "Trying to use a global variable without locking."
But I cannot see any harm for the reported functions, could someone describe more about the harm for this kind of potential bugs?

**Comment by Machiry** [comment]
These warnings are raised when a global variable is used without holding a lock. There could be potential race conditions, ideally, all global variables should be used by holding locks.

However, I agree with you. Depending on the usage, these may or may not be a security issue.
Btw, You can ignore these errors by enabling a flag in the code: https://github.com/ucsb-seclab/dr_checker/blob/speedy/llvm_analysis/MainAnalysisPasses/SoundyAliasAnalysis/src/bug_detectors/BugDetectorDriver.cpp#L26
